# NumPy

NumPy is a first-rate library for numerical programming

**Widely used in academia, finance and industry**

**Mature, fast, stable and under continuous development**

The most important of these dtypes are:

**float64**: 64 bit floating-point number

**int64**: 64 bit integer

**bool**: 8 bit True or False

In [1]:
import numpy as np

In [2]:
a = np.zeros(3)

print(a)

print(type(a))

[0. 0. 0.]
<class 'numpy.ndarray'>


In [3]:
a = np.zeros(3)

print(type(a[0]))

<class 'numpy.float64'>


In [4]:
a = np.zeros(3, dtype=int)

print(type(a[0]))

<class 'numpy.int64'>


# Shape and Dimension

In [5]:
z = np.zeros(10)

z.shape

(10,)

In [6]:
z.shape = (10, 1)

z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [7]:
z = np.zeros(4)

z.shape = (2, 2)

z

array([[0., 0.],
       [0., 0.]])

In [8]:
z = np.zeros((2, 2))

z

array([[0., 0.],
       [0., 0.]])

In [9]:
w = np.empty(3)

w

array([0., 0., 0.])

In [10]:
w = np.linspace(2, 4, 5)

w

array([2. , 2.5, 3. , 3.5, 4. ])

In [11]:
y = np.identity(2)

y

array([[1., 0.],
       [0., 1.]])

In [12]:
q = np.array([10, 20])

print(q)

print(type(q))

[10 20]
<class 'numpy.ndarray'>


In [13]:
z = np.array((10, 20), dtype=float)

z

array([10., 20.])

In [14]:
z = np.array([[1, 2], [3, 4]]) 

z

array([[1, 2],
       [3, 4]])

In [15]:
na = np.linspace(10, 20, 2)

na is np.asarray(na)

True

In [16]:
 na is np.array(na)

False

In [17]:
z = np.linspace(1, 2, 5)
    
z

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [18]:
z[0]

1.0

In [19]:
z[0:2]

array([1.  , 1.25])

In [20]:
z[-1]

2.0

In [21]:
z = np.array([[1, 2], [3, 4]])
z

array([[1, 2],
       [3, 4]])

In [22]:
z[0, 0]

1

In [23]:
z[0, 1]

2

In [24]:
z = np.linspace(2, 4, 5)

z

array([2. , 2.5, 3. , 3.5, 4. ])

In [25]:
indices = np.array((0, 2, 3))

z[indices]

array([2. , 3. , 3.5])

In [26]:
d = np.array([0, 1, 1, 0, 0], dtype=bool)

d

array([False,  True,  True, False, False])

In [27]:
z = np.empty(3)

z

array([2. , 3. , 3.5])

In [28]:
z[:] = 42

z

array([42., 42., 42.])

In [29]:
a = np.array((4, 3, 2, 1))

a

array([4, 3, 2, 1])

In [30]:
a.sort() # Sorts a in place

a

array([1, 2, 3, 4])

In [31]:
a.sum()

10

In [32]:
a.mean()

2.5

In [33]:
a.max()

4

In [34]:
a.argmax()

3

In [35]:
a.cumsum()

array([ 1,  3,  6, 10])

In [36]:
a.cumprod()

array([ 1,  2,  6, 24])

In [37]:
a.var()

1.25

In [38]:
a.std()

1.118033988749895

In [39]:
a.shape = (2, 2)

a.T 

array([[1, 3],
       [2, 4]])

In [40]:
z.searchsorted(2.2)

0

In [41]:
a = np.array((4, 3, 2, 1))

In [42]:
np.sum(a)

10

In [43]:
np.mean(a)

2.5

# Operations on arrays

**Arithmetic Operations**

In [44]:
a = np.array([1, 2, 3, 4])

b = np.array([5, 6, 7, 8])

In [45]:
a + b

array([ 6,  8, 10, 12])

In [46]:
a - b

array([-4, -4, -4, -4])

In [47]:
a * b

array([ 5, 12, 21, 32])

In [48]:
a / b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [49]:
a**b

array([    1,    64,  2187, 65536])

In [50]:
b**a

array([   5,   36,  343, 4096])

In [51]:
b/a

array([5.        , 3.        , 2.33333333, 2.        ])

In [52]:
A = np.ones((2, 2))
B = np.ones((2, 2))

In [53]:
A + B

array([[2., 2.],
       [2., 2.]])

In [54]:
A - B

array([[0., 0.],
       [0., 0.]])

In [55]:
A * B #In particular, A * B is not the matrix product, it is an element-wise product.

array([[1., 1.],
       [1., 1.]])

In [56]:
A / B

array([[1., 1.],
       [1., 1.]])

In [57]:
A ** B

array([[1., 1.],
       [1., 1.]])

**Matrix Multiplication**

In [58]:
A = np.ones((2, 2))
B = np.ones((2, 2))
A @ B

array([[2., 2.],
       [2., 2.]])

In [59]:
A = np.array((1, 2))
B = np.array((10, 20))
A @ B

50

In [60]:
A = np.array(((1, 2), (3, 4)))
A

array([[1, 2],
       [3, 4]])

In [61]:
A @ (0, 1)

array([2, 4])

**Mutability and Copying Arrays**

NumPy arrays are mutable data types, like Python lists

In [62]:
a = np.array([42, 44])
a

array([42, 44])

In [63]:
a[0] = -1

a

array([-1, 44])

In [64]:
a[1] = 10

a

array([-1, 10])

In [65]:
a = np.random.randn(3)

a

array([ 1.27066588, -0.10482878, -0.12924169])

In [66]:
b = a
b[0] = 0.0
a

array([ 0.        , -0.10482878, -0.12924169])

In [67]:
b == a

array([ True,  True,  True])

In [68]:
c = np.random.randn(5)

c

array([ 2.04662374e-01, -3.95401152e-01,  8.28321399e-05, -8.43365468e-01,
        4.96278853e-01])

In [69]:
d = np.copy(c)

d

array([ 2.04662374e-01, -3.95401152e-01,  8.28321399e-05, -8.43365468e-01,
        4.96278853e-01])

In [70]:
d[:] = 1.74783393
d

array([1.74783393, 1.74783393, 1.74783393, 1.74783393, 1.74783393])

In [71]:
c == d

array([False, False, False, False, False])

**Vectorized Functions**

NumPy provides versions of the standard functions log, exp, sin, etc. that act elementwise on arrays

In [72]:
z = np.array([1, 2, 3])
np.sin(z)

array([0.84147098, 0.90929743, 0.14112001])

In [73]:
(1 / np.sqrt(2 * np.pi)) * np.exp(- 0.5 * z**2)

array([0.24197072, 0.05399097, 0.00443185])

In [74]:
x = np.random.randn(4)
x

array([-1.73158802,  0.80042789,  0.30589621, -0.60791559])

In [75]:
np.where(x > 0, 1, 0)

array([0, 1, 1, 0])

In [78]:
def f(x):
    return 1 if x > 0 else 0

f = np.vectorize(f)
f(x)

array([0, 1, 1, 0])

**Comparisons**

In [79]:
z = np.array([2, 3])
y = np.array([2, 3])
z == y

array([ True,  True])

In [80]:
y[0] = 5
z == y

array([False,  True])

In [81]:
z != y

array([ True, False])

In [82]:
z = np.linspace(0, 10, 5)
z

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [85]:
y = np.linspace(1,12,6)
y

array([ 1. ,  3.2,  5.4,  7.6,  9.8, 12. ])

In [86]:
y > 3

array([False,  True,  True,  True,  True,  True])

In [87]:
y < 4

array([ True,  True, False, False, False, False])

In [88]:
b = y > 3
b

array([False,  True,  True,  True,  True,  True])

In [89]:
y[b]

array([ 3.2,  5.4,  7.6,  9.8, 12. ])

In [90]:
y[y>3]

array([ 3.2,  5.4,  7.6,  9.8, 12. ])

**Sub-packages**

NumPy provides some additional functionality related to scientific programming through its sub-packages.

We’ve already seen how we can generate random variables using np.random

In [91]:
x = np.random.randn(10000)
y = np.random.binomial(10, 0.5, size=1000)

In [92]:
y.mean()

5.003

In [96]:
A = np.array([[1, 2], [3, 4]])

np.linalg.det(A)  # Compute the determinant

-2.0000000000000004

In [99]:
 np.linalg.inv(A)  # Compute the inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# Exercise 1

Consider the polynomial expression
𝑝(𝑥) = 𝑎0 + 𝑎1𝑥 + 𝑎2𝑥2 + ⋯ 𝑎𝑁𝑥𝑁 = 𝑁∑ 𝑎𝑛𝑥𝑛
𝑛=0


Earlier, you wrote a simple function p(x, coeff) to evaluate (1) without considering efficiency.

Now write a new function that does the same job, but uses NumPy arrays and array operations for its computations, rather than any form of Python loop.

In [100]:
import matplotlib.pyplot as plt
%matplotlib inline

In [101]:
def p(x, coef):
    X = np.ones_like(coef)
    X[1:] = x
    y = np.cumprod(X) # y = [1, x, x**2,...]
    return coef @ y

In [104]:
x = 2
coef = np.linspace(2, 4, 3)
print(coef)
print(p(x, coef))
# For comparison
q = np.poly1d(np.flip(coef))
print(q(x))

[2. 3. 4.]
24.0
24.0
